############################################################################
#
#   Copyright (C) 2000, Microsoft Corporation.
#
#   All rights reserved.
#
############################################################################

!ifdef NTMAKEENV

!include $(NTMAKEENV)\makefile.def

!else # NTMAKEENV

default: all

!include filelist.mk
!include $(COMMON)\src\win40.mk

!endif # NTMAKEENV
