//+---------------------------------------------------------------------------
//
//  Microsoft Windows
//  Copyright (C) Microsoft Corporation, 2000 - 2000.
//
//  File:	headers.cxx
//
//  Contents:	scm precompiled headers
//
//  Classes:	
//
//  Functions:	
//
//  History:	24-Aug-93	PhilipLa	Created
//
//----------------------------------------------------------------------------

#include    <rpc.h>
#include    <windows.h>
#include    <except.hxx>
#include    <ole2.h>




