/*++ BUILD Version: 0001    // Increment this if a change has global effects

Copyright (c) 2000  Microsoft Corporation

Module Name:

    srvif.h

Abstract:

    Server adminstrative interface

Author:

    Dan Hinsley (danhi) 8-Jun-2000

Environment:

    User Mode - Win32
    Portable to any flat, 32-bit environment.  (Uses Win32 typedefs.)
    Requires ANSI C extensions: slash-slash comments.

--*/
#define ADMIN_SHARE	TEXT("ADMIN$")
#define IPC_SHARE	TEXT("IPC$")
