#********************************************************************
#**                     Microsoft Windows                          **
#**               Copyright(c) Microsoft Corp., 2000 - 1994        **
#********************************************************************

default: all
!include filelist.mk
!include $(COMMON)\src\win40.mk
!include $(DEPENDFILE)
