//=============================================================================
//  Microsoft (R) Bloodhound (tm). Copyright (C) 2000-1993.
//
//  MODULE: conndlg.h
//
//  Modification History
//
//  tonyci       Dec 1993            Created 
//=============================================================================

extern PCONNECTION WINAPI NalConnectionDlg ();
extern BOOL CALLBACK NalConnectionDlgProc (HWND, UINT, WPARAM, LPARAM);
