//=============================================================================
//  Microsoft (R) Bloodhound (tm). Copyright (C) 2000-1993.
//
//  MODULE: recondlg.h
//
//  Modification History
//
//  tonyci       Dec 1993            Created 
//=============================================================================

extern DWORD WINAPI NalReconnectionDlg ();
extern BOOL CALLBACK NalReconnectionDlgProc (HWND, UINT, WPARAM, LPARAM);

