//=============================================================================
//  Microsoft (R) Bloodhound (tm). Copyright (C) 2000-1993.
//
//  MODULE: misc.h
//
//  MODIFICATION HISTORY:
//
//  raypa       01/15/93        Created.
//=============================================================================

//=============================================================================
//  external funtions defined in misc.c
//=============================================================================

extern HBUFFER WINAPI MapBufferTable(HBUFFER hBuffer);

extern HBUFFER WINAPI UnmapBufferTable(HBUFFER hBuffer);
