//--------------------------------------------------------------------------
//
// Module Name:  PSPROC.H
//
// Brief Description:  This module contains global defines and structures
//		       necessary for the PSCRIPT driver to access the PS Procset
//             resources.
//
// Author:  Rob Kiesler
// Created: 21-Jan-1993
//
//
// Copyright (c) 2000, 2000 Microsoft Corporation
//
//--------------------------------------------------------------------------
#define UTILS 1
#define PATTERN 2
#define IMAGE 3
