/**********************************************************************/
/**                       Microsoft Windows/NT                       **/
/**                Copyright(c) Microsoft Corp., 2000                **/
/**********************************************************************/

/*
    uimisc.hxx
    Miscellaneous UI function declarations

    These functions fit nowhere else.  Please help them find a home.

    FILE HISTORY:
        rustanl     31-Jan-2000 Created.  Added LoadResourceString
        rustanl     09-Apr-2000 Added QueryCurrentTimeStamp
        beng        07-Oct-2000 LoadR.S. uses contemporary typedefs
        beng        27-Jul-2000 Nuke LoadResourceString
*/


#ifndef _UIMISC_HXX_
#define _UIMISC_HXX_


ULONG QueryCurrentTimeStamp();


#endif  // _UIMISC_HXX_
