############################################################################
#
#   Copyright (C) 2000, Microsoft Corporation.
#
#   All rights reserved.
#
############################################################################

default: all
!include filelist.mk
!include $(COMMON)\src\win40.mk
!include depend.mk

