/*++

Copyright (c) 2000  Microsoft Corporation

Module Name:

    arcutils.h

Abstract:

    Top-level export include file for functions in the
    ARC utility code (fdisk,format).

Author:

    Ted Miller        (tedm)    8-Nov-2000

Revision History:

--*/

#ifndef _ARCUTILS_
#define _ARCUTILS_

#ifdef ARC
#include "arclib.h"
#endif

#include "autildef.h"
#include "fmtexp.h"
#include "alpartit.h"

#endif
