 /*****************************************************************************
 *
 *  Graph.h - Header for graphing window.
 *
 *  Microsoft Confidential
 *  Copyright (c) 2000-1993 Microsoft Corporation
 *
 *
 ****************************************************************************/


#define GRAPH_BORDER 4


BOOL GraphInitializeApplication (void) ;


HWND CreateGraphWindow (HWND hWndParent) ;


void SizeGraphComponents (HWND hWnd) ;


