/**********************************************************************/
/**			  Microsoft Windows/NT			     **/
/**		   Copyright(c) Microsoft Corp., 2000		     **/
/**********************************************************************/

/*

    ErrorNum.h - Defines base manifests for error numbers and string IDs


    FILE HISTORY:
	Johnl	15-Apr-2000	Created


*/

#ifndef _ERRORNUM_H_
#define _ERRORNUM_H_

#define










#endif // _ERRORNUM_H_
