//+-------------------------------------------------------------------------
//
//  Microsoft Windows
//  Copyright (C) Microsoft Corporation, 2000 - 2000.
//
//  File:       PCH.CXX
//
//  Contents:   Precompiled header
//
//  History:    12-Jul-93 ShannonC  Created
//
//--------------------------------------------------------------------------
#pragma warning(disable:4101)  // Local variable not used

#include <windows.h>
#include <ole2.h>
#include "stdrpc.hxx"
#pragma hdrstop
