
/******************************************************************************
Copyright (c) Maynard, an Archive Company.  2000
GSH

     Name:          cursors.h

     Description:   This file contains the CURSOR IDs for the Maynstream GUI
                    project.

     $Log:   G:/UI/LOGFILES/CURSORS.H_V  $

   Rev 1.2   04 Oct 2000 19:46:28   DAVEV
UNICODE AWK PASS

   Rev 1.1   26 Mar 2000 08:53:08   GLENN
Added new pen.

   Rev 1.0   20 Nov 2000 19:36:04   SYSTEM
Initial revision.

******************************************************************************/

// CURSOR RESOURCE IDs

// Windows Internal Cursors.

#define IDRC_ARROW            IDC_ARROW
#define IDRC_WAIT             IDC_WAIT
#define IDRC_IBEAM            IDC_IBEAM

// GUI Subsystem Cursors. -- RANGE: 21 - 30

#define IDRC_PEN              ID(21)
#define IDRC_HAND             ID(22)
#define IDRC_HSLIDER          ID(23)
#define IDRC_HELP             ID(24)
#define IDRC_PEN2             ID(25)
