
/******************************************************************************
Copyright (c) Maynard, an Archive Company.  2000
GSH

     Name:          keys.h

     Description:   This file contains the ACCELERATOR KEY IDs and
                    miscellaneous key IDs for the Maynstream GUI project.

     $Log:   G:/UI/LOGFILES/KEYS.H_V  $

   Rev 1.2   04 Oct 2000 19:47:36   DAVEV
UNICODE AWK PASS

   Rev 1.1   03 Dec 2000 16:04:52   GLENN
Remove old ribbon accel keys - no longer used.  Added some Virtual Keys.

   Rev 1.0   20 Nov 2000 19:37:06   SYSTEM
Initial revision.

******************************************************************************/


#ifndef _KEYS_H
#define _KEYS_H

// WINDOWS ACCELERATOR KEY ID's

#define IDRA_ACCKEYS          ID(1)


#define VK_8                  0x38
#define VK_OEM_PLUS           0xBB
#define VK_OEM_MINUS          0xBD

#endif
