/*******************************************************************************
Copyright(c) Maynard, an Archive Company.  2000


     Name:         tension.h

     Description:  include file for the tension.dlg dialog


     $Log:   G:/UI/LOGFILES/TENSION.H_V  $

   Rev 1.3   04 Oct 2000 19:49:46   DAVEV
UNICODE AWK PASS

   Rev 1.2   03 Apr 2000 13:52:44   CARLS
added translate defines

   Rev 1.0   20 Nov 2000 19:34:42   SYSTEM
Initial revision.

*******************************************************************************/

#ifdef TRANSLATE
#define IDHELP 100
#define IDD_TENSION       41
#endif

#define IDD_JST_LISTBOX   67
#define IDD_JST_OK        220

