/****************************** Module Header ******************************\
* Module Name: DosLog.h
*
* Copyright (c) 2000, Microsoft Corporation
*
* Contains definitions of Dos boot/shutdown support functions
*
* Currently NONE
*
* History:
* 04-30-92 Sudeepb  Created.
*
* 25-Nov-2000 Jonle, removed winlogon renaming
\***************************************************************************/

void BootDOS ( void ) ;
void ShutdownDOS ( void );
