/****************************** Module Header ******************************\
* Module Name: lock.h
*
* Copyright (c) 2000, Microsoft Corporation
*
* Define apis used to lock the workstation
*
* History:
* 12-09-91 Davidc       Created.
\***************************************************************************/


//
// Exported function prototypes
//


BOOL
LockWorkstation(
    PGLOBALS
    );


