############################################################################
#
#   Copyright (C) 2000, Microsoft Corporation.
#
#   All rights reserved.
#
############################################################################

default: all
!include filelist.mk
!include $(COMMON)\src\win40.mk

MIDL=$(TOOLPATH)\midl76.exe

all:	$(OBJS)

!include depend.mk
