/**********************************************************************/
/**                       Microsoft LAN Manager                      **/
/**                Copyright(c) Microsoft Corp., 2000                **/
/**********************************************************************/

/*
    setsel.h
    Set Selection dialog manifests


    FILE HISTORY:
        rustanl     16-Aug-2000 Created
        beng        01-Apr-2000 Inserted SZs.
        JonN        02-Apr-2000 Load by ordinal only
        beng        04-Aug-2000 Move into range
*/


#ifndef _SETSEL_H_
#define _SETSEL_H_

#define IDD_SETSEL_DLG              2000

#define IDC_SETSEL_GROUP_TEXT       7501
#define IDC_SETSEL_GROUP_LB         7502
#define IDC_SETSEL_SELECT           7503
#define IDC_SETSEL_DESELECT         7504


#endif  // _SETSEL_H_
