//+-------------------------------------------------------------------------
//
//  Microsoft Windows
//  Copyright (C) Microsoft Corporation, 2000 - 2000.
//
//  File:	msfhead.cxx
//
//  Contents:	Precompiled headers
//
//--------------------------------------------------------------------------



#include <msf.hxx>
#include <header.hxx>
#include <vect.hxx>
#include <page.hxx>
#include <vectfunc.hxx>
#include <fat.hxx>
#include <dir.hxx>
