/*****************************************************************/ 
/**		     Microsoft LAN Manager			**/ 
/**	       Copyright(c) Microsoft Corp., 2000-1990		**/ 
/*****************************************************************/ 

/*
 *	Windows/Network Interface  --  LAN Manager Version
 *
 *	These manifests are used in the Find Printer and Set Focus dialogs.
 */

#include "pmandlg.h"

#undef  PMAN_HELP
#define PMAN_HELP   IDHELP
