/*****************************************************************************
*                                                                            *
*  FRCHECK.EXT                                                               *
*                                                                            *
*  Copyright (C) Microsoft Corporation 2000.                                 *
*  All Rights reserved.                                                      *
*                                                                            *
******************************************************************************
*                                                                            *
*  Module Intent:  Prototype frcheck routines.                               *
*                                                                            *
******************************************************************************
*                                                                            *
*  Current Owner: Dann
*                                                                            *
******************************************************************************
*                                                                            *
*  Released by Development:  awhile ago.                                     *
*                                                                            *
*****************************************************************************/


BOOL PASCAL FVerifyQMOPG(QMOPG);
BOOL PASCAL FVerifyQMSBS(QDE, QMSBS, SDFF_FILEID );
