;	INTL.S
;
;	SERVER.CSI string literals that should be internationalized
;

IDS	4500, 4599

;
; Details box captions
;
AddrTypeText,		"Adresstyper:"
MacMailText,		"Macixposh Nätverk"
CourierText,		"PC Mail"
UserNameText,		"Användarnamn:"
ServerText,		"Postkontor:"
NetworkText,		"Nätverk:"
PostOfficeText,		"Postkontor:"
MailBoxText,		"Inloggningsnamn:"

;
; Different name types in addressing dialog dropdown

PersonalTag,		"Personlig"
LocalTag,		"Lokalt postkontor"
NetworkTag,		"Nätverk"
MSMailTag,		"Macixposh Nätverk"


;
; Added error message for retrying file errors in admin program'

RetryWrite,			"Kunde inte skriva till kalenderfilen."

