md \xp\neptune\crt32
cd \xp\neptune\crt32
enlist -vfs \\orville\razzle -p crt32
md \xp\neptune\crt32nt
cd \xp\neptune\crt32nt
enlist -vfs \\orville\razzle -p crt32
md \xp\neptune\crt32st
cd \xp\neptune\crt32st
enlist -vfs \\orville\razzle -p crt32
md \xp\neptune\crt32dll
cd \xp\neptune\crt32dll
enlist -vfs \\orville\razzle -p crt32
md \xp\neptune\crt32psx
cd \xp\neptune\crt32psx
enlist -vfs \\orville\razzle -p crt32
md \xp\neptune\fp32
cd \xp\neptune\fp32
enlist -vfs \\orville\razzle -p fp32
cd tools.mak
ssync -gr
md \xp\neptune\fp32nt
cd \xp\neptune\fp32nt
enlist -vfs \\orville\razzle -p fp32
cd tools.mak
ssync -gr
md \xp\neptune\fp32st
cd \xp\neptune\fp32st
enlist -vfs \\orville\razzle -p fp32
cd tools.mak
ssync -gr
md \xp\neptune\fp32dll
cd \xp\neptune\fp32dll
enlist -vfs \\orville\razzle -p fp32
cd tools.mak
ssync -gr
md \xp\neptune\crtlib
cd \xp\neptune\crtlib
enlist -vfs \\orville\razzle -p crtlib
