//+---------------------------------------------------------------------------
//
//  Microsoft Windows
//  Copyright (C) Microsoft Corporation, 2000 - 2000.
//
//  File:	headers.hxx
//
//  Contents:	class precompiled headers
//
//  Classes:	
//
//  Functions:	
//
//  History:	24-Aug-93	PhilipLa	Created
//
//----------------------------------------------------------------------------
#include <windows.h>
#include <ole2.h>
#include <com.hxx>
#include "safepnt.hxx"
#include  "olesrv.hxx"
