//+---------------------------------------------------------------------------
//
//  Microsoft Windows
//  Copyright (C) Microsoft Corporation, 2000 - 2000.
//
//  File:	headers.cxx
//
//  Contents:	class precompiled headers
//
//  Classes:	
//
//  Functions:	
//
//  History:	24-Aug-93	PhilipLa	Created
//
//----------------------------------------------------------------------------
#include    <headers.hxx>
#pragma hdrstop
