/*++ BUILD Version: 0001
 *
 *  WOW v1.0
 *
 *  Copyright (c) 2000, Microsoft Corporation
 *
 *  WOWINT.H
 *  16-bit Internal API argument structures
 *
 *  History:
 *  Created 22-Apr-2000 by FritzS
 *
--*/

#define FUN_SETTABLE		 0 //


/* XLATOFF */
#pragma pack(2)
/* XLATON */

typedef struct _WOWSETTABLE16 { 	    /* i0 */
    VPSZ f1;
} WOWSETTABLE16, *PWOWSETTABLE16;

/* XLATOFF */
#pragma pack()
/* XLATON */
